version: "3"
services:
  mongodb:
    image : davybello/mongo-replica-set:4.4.8
    container_name: mongodb
    volumes:
      - "./docker/.data/mongo1:/var/lib/mongo1"
      - "./docker/.data/mongo2:/var/lib/mongo2"
      - "./docker/.data/mongo3:/var/lib/mongo3"
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019