spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_DB:mongodb}:27017 # ,${MONGO_DB:mongodb}:27018,${MONGO_DB:mongodb}:27019
      database: readingisgood
      auto-index-creation: true

jwt:
  secretKey: ${SECRET_KEY:reading-is-good}
  accessTokenExpiration: ${ACCESS_TOKEN_EXPIRE:3600000}